controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_program:
    path: /program
    controller: 'App\Controller\ProgramController::index'
    methods: GET

program_show:
    path: /program/{id<\d+>}/
    controller: 'App\Controller\ProgramController::show'
    methods: GET
    requirements:
        id: '\d+'

program_season_show:
    path: /program/{programId}/seasons/{seasonId}
    controller: App\Controller\ProgramController::showEpisodes
    methods: GET